config/routes.rb
Rails.application.routes.draw do

  root 'people#index'

  resources :people do
    resources :birth_certificates
  end
end

app/models/birth_certificate.rb
class BirthCertificate < ActiveRecord::Base
  belongs_to :person
  before_create :assign_date_of_issue

  private
  def assign_date_of_issue
    self.date_of_issue = Time.now
  end
end

app/models/person.rb
class Person < ActiveRecord::Base
  before_create :generate_aadhar_number, :generate_birth_certificate

  validates :name, presence: true
  has_one :birth_certificate

  private
  def generate_aadhar_number
    self.aadharNum = (rand(10 ** 11) + Time.now.hash.abs.to_s[0..8].to_i).to_s
  end

  def generate_birth_certificate
    self.birth_certificate = BirthCertificate.new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/birth_certificates_controller.rb
class BirthCertificatesController < ApplicationController
  def show

    @cert = BirthCertificate.find(params[:id])
    @person = Person.find(@cert.person)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  def new
    @person = Person.new
  end

  def create
    @person = Person.new(sanitise_params)
    if @person.save
      redirect_to @person
    else
      render 'new'
    end
  end

  def show
    @person = Person.find(params[:id])
  end

  def index
    @people = Person.all
  end

  private
  def sanitise_params
    params.require(:person).permit(:name, :address, :dob)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/birth_certificates_helper.rb
module BirthCertificatesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/birth_certificates/show.html.erb
<p>Issued by India Gov </p>
<p>Date of Issue <%= @cert.date_of_issue %></p>
<p> For <%= @person.name %></p>
<p> DOB <%= @person.dob%></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aadhar</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/index.html.erb
<table>
  <tr>
    <th>
      Name
    </th>
    <th>
      Address
    </th>
  </tr>
  <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.address %></td>
        <td><%= person.dob %></td>
        <td><%= person.aadharNum %></td>
        <td><%= link_to("Birth certificate", person_birth_certificate_path(person, person.birth_certificate)) unless person.birth_certificate.nil? %></td>
      </tr>
  <% end %>

</table>

app/views/people/new.html.erb
<%= form_for :person, url: people_path do |f| %>
    <% if @person.errors.any? %>
        <p> All inputs are mandatory </p>
    <% end %>
    <p>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </p>
    <p>
      <%= f.label :address %>
      <%= f.text_area :address %>
    </p>
    <p>
      <%= f.label :dob %>
      <%= f.date_field :dob %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

app/views/people/show.html.erb
<p>
  Name: <%= @person.name %>
  Address : <%= @person.address %>
  Aadhar number : <%= @person.aadharNum %>
</p>